title: Yan Shijin's Homepage
page-top-title: Yan Shijin
top-section-bg-text: Artificial Intelligence
home-subtitle: Yan Shijin&ensp;|&ensp;严世锦
copyright-text: '&copy; Yan Shijin 2025. All Rights Reserved.'
